name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: deno install
      - name: Lint
        run: deno lint
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: deno install
      - name: Type check
        run: deno check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: deno install
      - name: Test
        run: deno test -A --coverage=coverage
      - name: Generate lcov report
        run: deno coverage --lcov coverage/ --output=cov.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./cov.lcov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: d2verb/pera
