name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: page
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
      - name: Install dependencies
        working-directory: docs
        run: deno install
      - name: Generate documentation
        working-directory: docs
        run: deno run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        working-directory: docs
        with:
          path: .vitepress/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
