name: Publish to JSR
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: denoland/setup-deno@v2
      - name: Publish to JSR
        run: deno publish
